// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
    MY_BUCKET: R2Bucket;
    OSS_PREFIX: string;
    JWT_SECRET: string;
    INTERNAL_API_KEY: string;
}
